jedis :
  pool :
    host : 127.0.0.1
    port : 6379
    config :
      maxTotal: 100
      maxIdle: 20
      maxWaitMillis : 100000

server :
  port : 8081

spring:
    http:
        multipart:
            max-file-size: 100MB
            max-request-size: 100MB

shitdata:
    url: jdbc:mysql://127.0.0.1:3306/db_test
    username: root
    password: 123456
