jedis :
  pool :
    host : 127.0.0.1
    port : 6379
    config :
      maxTotal: 100
      maxIdle: 20
      maxWaitMillis : 100000

server :
  port : 8081

spring:
    http:
        multipart:
            max-file-size: 100MB
            max-request-size: 100MB

datasource:
        name: hud
        url: jdbc:mysql://127.0.0.1:3306/tos
        username: root
        password: root
        # 使用druid数据源
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        maxActive: 20
        initialSize: 1
        maxWait: 60000
        maxIdle: 20
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20
